# ==========================
# FONT
# ==========================

font_family JetBrainsMono Nerd Font Mono
font_size 12

# Ligaduras
disable_ligatures never


# ==========================
# AMOLED THEME
# ==========================

background #000000
foreground #e6e6e6

# Cursor
cursor #ffffff
cursor_text_color #000000

# Selección
selection_background #333333
selection_foreground #ffffff


# ==========================
# TRANSPARENCIA + BLUR
# ==========================

background_opacity 0.3

# ==========================
# PADDING
# ==========================

window_padding_width 12

# Esquinas
window_margin_width 0


# ==========================
# UI
# ==========================

hide_window_decorations yes

confirm_os_window_close 0

enable_audio_bell no


# ==========================
# TABLAS
# ==========================

tab_bar_style powerline
tab_bar_background #000000
active_tab_background #222222
active_tab_foreground #ffffff
inactive_tab_background #000000
inactive_tab_foreground #777777

shell /bin/zsh
